FROM openjdk:8-alpine
MAINTAINER openslice.io
COPY target/io.openslice.centrallog.service-0.0.1-SNAPSHOT.jar /opt/openslice/lib/
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/openslice/lib/io.openslice.centrallog.service-0.0.1-SNAPSHOT.jar"]