FROM adoptopenjdk/openjdk13-openj9:latest
MAINTAINER openslice.io
COPY target/io.openslice.centrallog.service-0.0.1-SNAPSHOT.jar /opt/openslice/lib/
ENTRYPOINT ["/usr/bin/java"]
CMD ["-Xshareclasses:cacheDir=/opt/shareclasses", "-jar", "/opt/openslice/lib/io.openslice.centrallog.service-0.0.1-SNAPSHOT.jar"]