
# For Spring Actuator /info endpoint
info:
    artifact: centrallog-service
    name: centrallog-service
    description: Spring centrallog-service
    version: 1.0.0

server:
  port: 13013
    

logging:
  level:
    org.springframework.cloud.consul: INFO
    org.apache.camel.zipkin: INFO
    org.apache.camel.spring.cloud: INFO
    org.apache.camel: INFO
  file: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
        
# Camel Service Call
camel:
  cloud:
    service-call.component: undertow
  zipkin:
    endpoint: http://localhost:9411/api/v2/spans
    server-service-mappings.[*]: centrallog-service
    client-service-mappings.[*]: centrallog-service
    include-message-body-streams: false
    
    
spring:
  profiles: default
  application:
    name: centrallog-service
  cloud:
    consul:
      enabled: true
      host: http://localhost
      port: 8500
      config:
        enabled: true
        prefix: config
        defaultContext: openslice
        data-key: osdata
        profileSeparator: '::'
        format: yaml
      discovery:        
        tags: openslice-microservice
        enabled: true
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        healthCheckInterval: 120s
      
  activemq:
    brokerUrl: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 100
    packages:
      trust-all: true

centrallogurl: "http://elk_ip:elk_port/index_name/_doc"

