
# For Spring Actuator /info endpoint
info:
    artifact: centrallog-service
    name: centrallog-service
    description: Spring centrallog-service
    version: 1.0.0

server:
  port: 13013
    

logging:
  level:
    org.apache.camel: INFO
  file: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
        
   
spring:
  config:
    activate:
      on-profile: "default"
  application:
    name: centrallog-service
  activemq:
    brokerUrl: tcp://localhost:61616?jms.watchTopicAdvisories=false
    user: artemis
    password: artemis
    pool:
      enabled: true
      max-connections: 100
    packages:
      trust-all: true

centrallogurl: "http://elk_ip:elk_port/index_name/_doc"

